function TestBehavioralCam(app)
        filename = CreateVideoRecordingScript(...
            [app.rootdir filesep 'Behavioral_MultiCam' filesep],...
            app.rootdir,...
            app.behav_cam_vals,...
            'record',0);
        cmd = sprintf('python "%s" && exit &',filename);
        system(cmd) 
end